// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpct5h-GhB5x4EUI5mQkVZ7nlSkmcXWSg',
    appId: '1:707536276606:web:6bf8b6165104a9736d1c2f',
    messagingSenderId: '707536276606',
    projectId: 'pbc-app-13e0f',
    authDomain: 'pbc-app-13e0f.firebaseapp.com',
    databaseURL:
        'https://pbc-app-13e0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pbc-app-13e0f.appspot.com',
    measurementId: 'G-JN9DM4M6NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIWQtonPs2ZEyXC8w9FaEHNpxfCVSJeIE',
    appId: '1:707536276606:android:a0fbe5d46889242b6d1c2f',
    messagingSenderId: '707536276606',
    projectId: 'pbc-app-13e0f',
    databaseURL:
        'https://pbc-app-13e0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pbc-app-13e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97J4oQTtW-7exabrwIP6clu782fLBTxs',
    appId: '1:707536276606:ios:f72507b826e6607c6d1c2f',
    messagingSenderId: '707536276606',
    projectId: 'pbc-app-13e0f',
    databaseURL:
        'https://pbc-app-13e0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pbc-app-13e0f.appspot.com',
    iosClientId:
        '707536276606-vji5gplt3c86ro9qukd4bkm6foi15hbb.apps.googleusercontent.com',
    iosBundleId: 'com.pbc.pbc',
  );
}
